In [1]:
import json
import pandas as pd
import geopandas as gpd
import folium

In [2]:
df = pd.read_csv('populacao_3.csv')

In [3]:
df

,uf,cidade,id,2001,2002,2003,2004,2005,2006,2007,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,AC,Acrelândia,1200013,8237.0,8454.0,8695.0,10668.0,11451.0,11786.0,11520.0,...,12779.0,13011.0,13353.0,13613.0,13869.0,14120.0,14366.0,15020.0,15256.0,15490.0
1,AC,Assis Brasil,1200054,3564.0,3611.0,3667.0,4852.0,5063.0,5153.0,5351.0,...,6192.0,6308.0,6480.0,6610.0,6738.0,6863.0,6986.0,7300.0,7417.0,7534.0
2,AC,Brasiléia,1200104,17384.0,17649.0,17944.0,16940.0,17721.0,18056.0,19065.0,...,21837.0,22261.0,22899.0,23378.0,23849.0,24311.0,24765.0,25848.0,26278.0,26702.0
3,AC,Bujari,1200138,6154.0,6382.0,6641.0,7654.0,8423.0,8751.0,6543.0,...,8629.0,8782.0,9003.0,9173.0,9339.0,9503.0,9664.0,10111.0,10266.0,10420.0
4,AC,Capixaba,1200179,5561.0,5814.0,6096.0,6287.0,7067.0,7403.0,8446.0,...,9088.0,9368.0,9836.0,10170.0,10498.0,10820.0,11136.0,11456.0,11733.0,12008.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,TO,Tocantínia,1721109,5807.0,5828.0,5846.0,5872.0,5906.0,5927.0,6663.0,...,6809.0,6880.0,7158.0,7236.0,7313.0,7387.0,7460.0,7471.0,7545.0,7617.0
5566,TO,Tupirama,1721257,1202.0,1217.0,1234.0,1259.0,1291.0,1311.0,1405.0,...,1605.0,1634.0,1718.0,1751.0,1782.0,1813.0,1843.0,1860.0,1891.0,1922.0
5567,TO,Tupiratins,1721307,1377.0,1395.0,1409.0,1429.0,1455.0,1471.0,2007.0,...,2154.0,2208.0,2342.0,2402.0,2461.0,2518.0,2574.0,2613.0,2671.0,2729.0
5568,TO,Wanderlândia,1722081,10370.0,10486.0,10585.0,10724.0,10908.0,11022.0,9317.0,...,11036.0,11088.0,11450.0,11509.0,11566.0,11622.0,11677.0,11631.0,11683.0,11734.0
5569,TO,Xambioá,1722107,12344.0,11984.0,12134.0,12345.0,12626.0,12799.0,10856.0,...,11471.0,11458.0,11736.0,11722.0,11709.0,11695.0,11683.0,11561.0,11540.0,11520.0

In [4]:
df.id = df.id.astype('str')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   uf      5570 non-null   object
 1   cidade  5570 non-null   object
 2   id      5570 non-null   object
 3   2001    5560 non-null   float64
 4   2002    5560 non-null   float64
 5   2003    5560 non-null   float64
 6   2004    5564 non-null   float64
 7   2005    5564 non-null   float64
 8   2006    5564 non-null   float64
 9   2007    5564 non-null   float64
 10  2008    5565 non-null   float64
 11  2009    5564 non-null   float64
 12  2010    5565 non-null   float64
 13  2011    5565 non-null   float64
 14  2012    5570 non-null   float64
 15  2013    5570 non-null   float64
 16  2014    5570 non-null   float64
 17  2015    5570 non-null   float64
 18  2016    5570 non-null   float64
 19  2017    5570 non-null   float64
 20  2018    5570 non-null   float64
 21  2019    5570 non-null   float64
 22  2020    5570 non-null   float64
dtypes: float64(20), object(3)
memory usage: 1001.0+ KB

In [6]:
# Salvando os dados percentuais
dicionario_mg = {}
for i in df[df.uf == 'MG'].index:
    # if df.loc[i][1] in ['Unaí', 'Paracatu', 'Moema', 'Lagoa da Prata', 'Luz', 'Bom Despacho']:
    perc = f'{((df.loc[i][-1]/df.loc[i][3])-1)*100:.2f}'
    #perc = perc.replace('.', ',')
    #print(perc,'|', df.loc[i][1], '|', df.loc[i][2])
    dicionario_mg[df.loc[i][1]] = [df.loc[i][1], df.loc[i][2], float(perc)]
        
#dicionario_mg

In [7]:
df_mg = pd.DataFrame(dicionario_mg.values(),columns=['cidade', 'id', 'percentual'])
df_mg

                     cidade       id  percentual
0       Abadia dos Dourados  3100104        8.77
1                    Abaeté  3100203        3.19
2                Abre Campo  3100302        0.75
3                   Acaiaca  3100401        2.02
4                   Açucena  3100500      -17.92
..                      ...      ...         ...
848                Virgínia  3171709       -0.62
849  Visconde do Rio Branco  3172004       29.87
850                  Viçosa  3171303       19.22
851            Volta Grande  3172103        5.88
852          Wenceslau Braz  3172202       -2.60

[853 rows x 3 columns]

In [8]:
# Pegando o geojson
url_geojson = 'mg.json'

geo_mg = gpd.read_file(url_geojson)

#geo_mg

In [9]:
# Levando os dados da taxa de mortalidade para dentro do objeto geoespacial
geo_mg = pd.merge(
    left = geo_mg,
    right = df_mg.filter(items=['id','percentual']), 
    on='id'
)

geo_mg

,id,name,description,geometry,percentual
0,3100104,Abadia dos Dourados,Abadia dos Dourados,"POLYGON ((-47.44410 -18.15847, -47.43543 -18.1...",8.77
1,3100203,Abaeté,Abaeté,"POLYGON ((-45.18200 -18.88757, -45.17314 -18.8...",3.19
2,3100302,Abre Campo,Abre Campo,"POLYGON ((-42.36955 -20.13218, -42.35755 -20.1...",0.75
3,3100401,Acaiaca,Acaiaca,"POLYGON ((-43.11391 -20.35784, -43.10969 -20.3...",2.02
4,3100500,Açucena,Açucena,"POLYGON ((-42.38592 -18.92388, -42.38140 -18.9...",-17.92
...,...,...,...,...,...
848,3171808,Virginópolis,Virginópolis,"POLYGON ((-42.70675 -18.66017, -42.68531 -18.6...",-1.77
849,3171907,Virgolândia,Virgolândia,"POLYGON ((-42.32194 -18.35613, -42.32256 -18.3...",-10.97
850,3172004,Visconde do Rio Branco,Visconde do Rio Branco,"POLYGON ((-42.88457 -20.93903, -42.88098 -20.9...",29.87
851,3172103,Volta Grande,Volta Grande,"POLYGON ((-42.53029 -21.69567, -42.52692 -21.7...",5.88
852,3172202,Wenceslau Braz,Wenceslau Braz,"POLYGON ((-45.33666 -22.51827, -45.34478 -22.5...",-2.60

In [13]:
%%timeit
# Criando o mapa base
mapa_folium = folium.Map(
    width = 800, 
    height = 600, 
    location = [-18.65, -45.61], 
    zoom_start = 6, 
    tiles = "cartodbpositron"
    #tiles = "OpenStreetMap"
)

# Criando a camada Choroplet
mapa = folium.Choropleth(
    geo_data = geo_mg,
    name ='choropleth',
    data = df_mg,
    columns = ['id','percentual'],
    key_on = 'feature.properties.id',
    fill_color = 'Reds',
    fill_opacity = 1.0,
    line_opacity = 0.9,
    line_color = 'grey', 
    line_weight = 0.25,
    legend_name = 'Variação percentual da população entre 2001 e 2020',
    highlight = True,
    reset = True 

).add_to(mapa_folium)

# Inserindo os rotulos ao passar o mouse
mapa.geojson.add_child(
  folium.features.GeoJsonTooltip(
      fields = ['name','id','percentual'],
      aliases = ['Município:','id:', 'Percentual:'],
      labels = True,
      localize = True,
      sticky = False,
  )
)

# Renderizando o mapa
mapa_folium

416 ms ± 9.09 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)